version: '3.8'

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: open-webui
    restart: unless-stopped
    ports:
      - "3000:8080"
    volumes:
      - open-webui:/app/backend/data

  pipelines:
    image: ghcr.io/open-webui/pipelines:latest
    container_name: pipelines
    restart: always
    ports:
      - "9099:9099"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:      
      - PIPELINES_DIR=/pipelines
      - PIPELINES_REQUIREMENTS_PATH=/pipelines 
    volumes:
      - ./pipelines:/pipelines

volumes:
  open-webui:
